apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-people-secret
spec:
  secretName: tls-people-secret
  dnsNames:
  - yourdomain.com
  acme:
    config:
    - http01:
        ingressClass: addon-http-application-routing
      domains:
      - yourdomain.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer